### ISSUE TITLE
more informative schema check

### ISSUE THREAD

**Issue by Whitford** [smog-server/OpenSMOG#31]
Currently, and XML issue will simply say 

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 170, in loadSystem
    self.loadXml(Xmlfile)
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 306, in loadXml
    raise ValueError("The xml file is not in the correct format")"

We should try to write out the message indicating what is wrong.  This is probably easy to add, but I don't know the syntax.  No rush, for now.  If one uses smog2, then they should comply, as long as they are using the right version of OpenSMOG.

**Comment by Whitford** [comment]
I modified this, so that the actual XML error is printed.
