### ISSUE TITLE
cryptic error message

### ISSUE THREAD

**Issue by Whitford** [smog-server/OpenSMOG#35]
I forgot to add a platform, and the error was very cryptic.

>>> sbm_CA2.loadSystem(Grofile=sbm_CA_grofile, Topfile=sbm_CA_topfile, Xmlfile=sbm_CA_xmlfile)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 177, in loadSystem
    self.loadTop(Topfile)
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 223, in loadTop
    self.forcesDict[self.forceNamesAA[force_id]] = force
AttributeError: 'SBM' object has no attribute 'forcesDict'
>>> sbm_CA2.saveFolder('output_2ci2_AA2')
>>> sbm_CA2.loadSystem(Grofile=sbm_CA_grofile, Topfile=sbm_CA_topfile, Xmlfile=sbm_CA_xmlfile)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 177, in loadSystem
    self.loadTop(Topfile)
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 223, in loadTop
    self.forcesDict[self.forceNamesAA[force_id]] = force
**AttributeError: 'SBM' object has no attribute 'forcesDict'**
>>> sbm_CA2.setup_openmm(platform='OpenCL',GPUindex='default')
>>> sbm_CA2.loadSystem(Grofile=sbm_CA_grofile, Topfile=sbm_CA_topfile, Xmlfile=sbm_CA_xmlfile)
creating force contact_gaussian from xml file
Files loaded in the system.

Perhaps we can add a check if setup_openmm was not called, then a specific message is provided that says "hey you, call setup_openmm!!"

**Comment by Whitford** [comment]
Since we give an example of exactly the sequence of calls with help(), I think it is probably unnecessary to check that people give the commands in the right order. If things were to run, and give the wrong answer, it would be more important.  But, as is, if they are the wrong order, nothing works.  I'm fine closing this ticket.

**Comment by junioreif** [comment]
A check function was created to check if setup_openmm() was setup before using  LoadSystem()
