### ISSUE TITLE
more cryptic messages

### ISSUE THREAD

**Issue by Whitford** [smog-server/OpenSMOG#37]
>>> sbm_CA3.createReporters(trajectory=True, energies=True, energy_components=False, interval=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 378, in createReporters
    self.simulation.reporters.append(DCDReporter(dcdfile, interval))
AttributeError: 'SBM' object has no attribute 'simulation'
>>> sbm_CA3.createSimulation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/whitford/miniconda3/envs/openSMOG/lib/python3.9/site-packages/OpenSMOG/OpenSMOG.py", line 336, in createSimulation
    self.simulation = Simulation(self.Top.topology, self.system, self.integrator, self.platform, self.properties) 
AttributeError: 'SBM' object has no attribute 'Top'
>>> sbm_CA3.loadSystem(Grofile=sbm_CA_grofile, Topfile=sbm_CA_topfile, Xmlfile=sbm_CA_xmlfile)creating force contact_gaussian from xml file
Files loaded in the system.

**Comment by Whitford** [comment]
Vinicius, is this still an issue?  From the original posting, I'm not even sure how to reproduce this.  I think we probably put in some checks that will prevent anyone from hitting it.  If you like, go ahead and close this issue.

**Comment by junioreif** [comment]
this type of issue arises when the system isn't initialized  (by setup_openmm()) now we have a check function to warn if it happens
